### ISSUE TITLE
Could you explain more what it does ?

### ISSUE THREAD

**Issue by ignatandrei** [JensDll/MinimalApiBuilder#14]
I want to add this code generator to my list of Roslyn Code Generators

 https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

Could you please explain how to use it?>
Thanks

**Comment by JensDll** [comment]
Sure, I can add a section to the `README`.

**Comment by ignatandrei** [comment]
Shared at https://ignatandrei.github.io/RSCG_Examples/v2/docs/MinimalApiBuilder
